apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::820625201572:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IDG5MZ31BWRY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::820625201572:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T23:49:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1529"
  uid: 361d3e3a-10a6-4e31-9a32-8feb21a53fbd
